name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2.4.1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install, lint, test, and build
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: deploy --only hosting
      env:
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
